all:
	javac -encoding UTF-8 -cp src src/main/*.java -d bin

run:
	java -cp bin main/Main

pack:
	del D:\Documents\Education\Matlog\matlog_task2.zip
	winrar a -afzip D:\Documents\Education\Matlog\matlog_task2.zip Makefile src bin