all:
	javac -encoding UTF-8 -cp src src/*.java -d bin

run:
	java -cp bin Main

pack:
	del D:\Documents\Education\Matlog\matlog_task1.zip
	winrar a -afzip D:\Documents\Education\Matlog\matlog_task1.zip Makefile src bin