/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class jni_JniExpNorm */

#ifndef _Included_jni_JniExpNorm
#define _Included_jni_JniExpNorm
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     jni_JniExpNorm
 * Method:    expNormA
 * Signature: (DD)D
 */
JNIEXPORT jdouble JNICALL Java_jni_JniExpNorm_expNormA
  (JNIEnv *, jobject, jdouble, jdouble);

/*
 * Class:     jni_JniExpNorm
 * Method:    expNormB
 * Signature: (DD)D
 */
JNIEXPORT jdouble JNICALL Java_jni_JniExpNorm_expNormB
  (JNIEnv *, jobject, jdouble, jdouble);

#ifdef __cplusplus
}
#endif
#endif
